### ISSUE TITLE
更新到0.0.2版本后无法使用

### ISSUE THREAD

**Issue by gyteng** [Srar/AlipayF2F#3]
前段时间看到这个项目，安装了0.0.1版本，测试了一下可以生成二维码。今天准备调试的时候发现更新到了0.0.2版本，然后同样的配置文件却不能使用了，就算使用express-sample里的默认配置也无法正确生成二维码，会提示如下信息：

`
支付宝签名验证失败 { alipay_trade_precreate_response: 
   { code: '40003',
     msg: 'Insufficient Conditions',
     sub_code: 'isv.missing-signature-config',
     sub_msg: '验签出错, 未配置对应签名算法的公钥或者证书' },
  sign: 'xxxxxxxx' }
`

我不知道还要提供哪些更具体的信息才能判断出问题在哪？

**Comment by Srar** [comment]
这位大佬 @guanbo  提交了pr #1 将RSA改为RSA2算法了. 

您只需要使用RSA2重新生成公钥和私钥并在蚂蚁金服后台设置就使用了.

**Comment by gyteng** [comment]
另外你首页README的地方`BEGIN RSA`前面少了一个横杠，需要5个

`
/* 公钥 和 私钥 的填写方式 */
    "testPrivateKey": "----BEGIN RSA PRIVATE KEY-----\n" +
`

**Comment by Srar** [comment]
好谢谢 我稍后更改
