### ISSUE TITLE
生成的二维码是失效的

### ISSUE THREAD

**Issue by cashyu** [Srar/AlipayF2F#7]
可以生成二维码，但是每次扫都提示码已失效

**Comment by Srar** [comment]
能提供截图吗？

**Comment by cashyu** [comment]
![image](https://cloud.githubusercontent.com/assets/20109390/23823138/e6d53286-0696-11e7-8ac2-5e3266a3adbd.png)
![image](https://cloud.githubusercontent.com/assets/20109390/23823137/e6d0fa18-0696-11e7-8167-1daaa19f57b5.png)

**Comment by Srar** [comment]
很尴尬这个问题我也没遇到过...我刚刚自己尝试了下是可以使用的...

不妨你看下`createQRPay `方法有个`timeExpress `参数来指定超时时间 单位为分钟 如果不填默认5分钟

我看了下你手机屏幕时间是`21:06`你回复时间是`21:15`也许可能是手机时间不正确也会导致这个问题

**Comment by cashyu** [comment]
你的本地环境也可以吗？　　localhost:3000

**Comment by Srar** [comment]
可以
