### ISSUE TITLE
在沙箱测试，返回信息支付宝签名验证失败

### ISSUE THREAD

**Issue by BluceLee0052** [Srar/AlipayF2F#8]
返回的数据是可以用的，下面是测试订单状态的返回信息。
{ message: '支付宝签名验证失败',
  info: 
   { alipay_trade_query_response: 
      { code: '10000',
        msg: 'Success',
        buyer_logon_id: 'fop***@sandbox.com',
        buyer_pay_amount: '350.00',
        buyer_user_id: '2088102171362436',
        fund_bill_list: [Object],
        invoice_amount: '350.00',
        open_id: '20881081972007708054988751113543',
        out_trade_no: '201703140000344',
        point_amount: '0.00',
        receipt_amount: '350.00',
        send_pay_date: '2017-03-14 00:15:38',
        total_amount: '350.00',
        trade_no: '2017031421001004430200360534',
        trade_status: 'TRADE_SUCCESS' },
     sign: 'DuXHIc3fJjXmTe0prTdh5QuQvW10FcS29ogHDVCSE8cP6vxcd12VB6yS/Kt4NZhHJmDtRdJC3v3YxLneYHe0H0xNbFCiZeUAsAYzPd2cy84t1NQ0X2OwcjXORD8D2OgKlwZCn0XsRH8SXFnsC6A9qEsrBn2BeJ0urUwkn5iZX88yIWsoucZh9ut9Nnv2IN4PxKoILMrlmVBcgDS5FPg09tr1+kxUZmM56jzJyqZSGyGYaoRcHQVD7u8lymNt/T/Zb3L88mIJO0ouLAehKgRGTzqu7VrLtGm9n2k28ayIzvRMVt4MxTA7Err0lQW7M1ezMWaElW9riJ3ozzDpmYXxHA==' } }

**Comment by Srar** [comment]
如果为空的话 默认会使用支付宝RSA(SHA1)公钥...您需要手动把RSA2(SHA256)公钥填进配置文件

**Comment by BluceLee0052** [comment]
merchantPrivateKey，alipayPublicKey，这两个我都配置了

**Comment by BluceLee0052** [comment]
配置的RSA2(SHA256)

**Comment by Srar** [comment]
配置截图看下？

**Comment by Srar** [comment]
好吧 我已经重现无法验签的问题了, 貌似是支付宝沙盒服务端问题 有几率会出现`sign`不正确问题. 你多点几次`生成支付二维码`试试

**Comment by BluceLee0052** [comment]
难道是人品问题，没有一次是验证正确的，
在问一个问题，if (invoiceStatus !== "TRADE_SUCCESS") {
            res.send("success")
        }   ，这个不是应该是invoiceStatus === TRADE_SUCCESS 才返回success吗？

**Comment by Srar** [comment]
支付宝有很多回调状态,  我偷懒只处理了用户支付后的回调.

**Comment by Srar** [comment]
![a](https://cloud.githubusercontent.com/assets/12068066/23891040/5787338c-08cf-11e7-96f2-b3372582c1db.gif)

**Comment by cashyu** [comment]
你的公钥和私钥用的什么工具生成的？

**Comment by Srar** [comment]
蚂蚁金服提供的那个生成工具生成的

**Comment by cashyu** [comment]
我的还是提示码已失效

**Comment by cashyu** [comment]
我就改了你example的配置文件，其余啥都没动

**Comment by Srar** [comment]
你试下我的配置文件

公钥
```
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtxR3kQ33SJUAXomyk6UTr7/tcIfwyf15z2Ml8vkenxevts7bRmSmU9NdNQP1cC4GC/ZENE4LGfhLPBDTfz7ve5cXKirfE7GAIBdVru21c1z7H545gmuw/NJIqWIjIQVzuF0X25Fr+feDrI4AfzK/Ju6JXsvAxSkc+7u6r/B3N/J/sfTrsD+ZqYpytyX4iStjAr591y6MkBOwarfVB8dfwrC1uM1IaRGaSEWQ6K5ZEPh52y+arDOww0e+3fORLnJMHAnG4w5AKl5ggIIXsq9SjunfTzW2IfMcpXK67UY+3rHhnOTaXG6a8KmO5UrsTuHIS0n7vagERHkfL+s+yK3u3QIDAQAB
```

`appid`, `notifyUrl`改成你自己的

[config.js.zip](https://github.com/Srar/AlipayF2F/files/840615/config.js.zip)

**Comment by BluceLee0052** [comment]
![image](https://cloud.githubusercontent.com/assets/9619268/23891583/13f78f06-08d2-11e7-8e8d-196b61a37be2.png)
这样配置有影响吗

**Comment by Srar** [comment]
你没加`\n`
![f6ad7e95-73e6-480f-812e-4fdec043b87a](https://cloud.githubusercontent.com/assets/12068066/23891915/7c826996-08d3-11e7-87eb-803089728906.png)

**Comment by cashyu** [comment]
还是提示码已失效

**Comment by Srar** [comment]
@cashyu 抱歉我刚刚把你们两搞混了 你那个问题 我这的确复现不了...

**Comment by cashyu** [comment]
![image](https://cloud.githubusercontent.com/assets/20109390/23892011/e010217e-08d3-11e7-9fa8-6bf34a15fff2.png)

**Comment by BluceLee0052** [comment]
@Srar  帮我把图片的notifyurl 划掉， 我这边加个\n报错

**Comment by cashyu** [comment]
![image](https://cloud.githubusercontent.com/assets/20109390/23892097/348700a6-08d4-11e7-8ce5-16f040862097.png)
@Srar  你扫我的试下

**Comment by Srar** [comment]
@cashyu 你的这个问题和和公钥私钥貌似没关系...建议你问下蚂蚁金服客服

**Comment by cashyu** [comment]
http://4d003ff0.viphk.ngrok.org

**Comment by Srar** [comment]
@cashyu 我扫你的也是提示已失效 还是问下客服吧

**Comment by cashyu** [comment]
好吧

**Comment by BluceLee0052** [comment]
@cashyu 我这边是可以的

**Comment by Srar** [comment]
@BluceLee0052 这样试下 

```
"merchantPrivateKey": "-----BEGIN RSA PRIVATE KEY-----\n" +
	"...你的私钥" +
	"\n-----END RSA PRIVATE KEY-----",
```

**Comment by BluceLee0052** [comment]
不行，还是提示验证失败

**Comment by Srar** [comment]
@BluceLee0052 加下Telegram __Srar000__

**Comment by cashyu** [comment]
问了客服，原来沙箱账号　必须要下载专门的沙箱支付宝app才能扫码

**Comment by Srar** [comment]
@cashyu 好吧 那麻烦你关闭 #7 谢谢..
